defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      layout: "default"
timezone: America/New_York
name: MakeMIT 2018
year: 2018

exclude: [bin, vendor, Gemfile, Gemfile.lock, makemit-splash.iml,README.md]